spring:
  main:
    web-application-type: none
  config:
    location: 'file:./config.properties'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.user}
    password: ${database.password}
    url: 'jdbc:mysql://${database.host}:${database.port}/${database.dbname}?createDatabaseIfNotExist=true'
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true